spring.datasource.url=jdbc:postgresql://localhost:5432/fintarget
spring.datasource.username=minjiwon
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.use-suffix-pattern=false

server.port=8080

jwt.secret=fintarget-secret-key-must-be-at-least-32-characters-long
jwt.expiration=3600000