spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintarget
    username: fintarget_user
    password: fintarget1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: TEMP_SECRET_KEY_REPLACE_AFTER_AUTH_TEAM_PROVIDES
